# Bajtazar discovers numpy

Bajtazar just recently got into python, but he is constantly complaining about how slow everything is. To stop his whining, you decided to show him that it's possible to write fast python code using numpy. Now Bajtazar gave you three tasks and he want you to show him how to do them in numpy without using any native python loops.

In [1]:
import numpy as np

### 1 Cyclic multiplication. - 3p
You probably know that numpy will broadcast multiplication if one of the dimensions is of size 1, but what if it could if one of the dimensions was a divisor of the other? Show to Bajtazar that you can do it for 1-D arrays. `cyclic_multiply` gets two 1-D arrays - `big` and `small`, where the `len(big) % len(small) == 0`. Your answer should be the pointwise multiplication of those two vectors, as if the `small` vector was repeated enough times to match it's size to the `big` vector. E.g if `big = [1, 2, 3, 4]` and `small = [1, 2]`, then you should return `[1*1, 2*2, 3*1, 4*2] = [1, 4, 3, 8]`

In [2]:
def cyclic_multiply(big: np.array, small: np.array) -> np.array:
    small_repeat = np.tile(small, int(len(big) / len(small)))
    return small_repeat * big

In [3]:
example_big = np.array([1, 2, 3, 4])
example_small = np.array([1, 2])

assert np.array_equal(cyclic_multiply(example_big, example_small), np.array([1, 4, 3, 8]))

### 2 How many flowers are in the sub-garden? - 4p

You are given a map of a garden as a 2-D array `garden`. Garden is divided into plots. `garden[i][j]` contains the information about how many flowers are on the the plot with coordinates `(i, j)`. Your task is to return the array `cumulative_garden` of the same size as garden, where `cumulative_garden[i][j]` contains the number of flowers inside the rectangle `(0, 0), (0, j), (i, 0), (i, j)`.


In [8]:
np.tri(2)

array([[1., 0.],
       [1., 1.]])

In [ ]:
def sub_gardens(garden: np.array) -> np.array:

    # neat solution
    cumulative_garden = np.tri(garden.shape[0]) @ garden @ np.tri(garden.shape[1]).T 

    # vert = np.cumsum(garden, axis=0)
    # cumulative_garden = np.cumsum(vert, axis=1)
    
    return cumulative_garden

example_garden = np.arange(1, 13).reshape(3, 4)
print(example_garden)
sub_gardens(example_garden)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1.,  3.,  6., 10.],
       [ 6., 14., 24., 36.],
       [15., 33., 54., 78.]])

In [11]:
example_garden = np.arange(1, 10).reshape(3, 3)
garden_correct = np.array([[ 1,  3,  6], 
                           [ 5, 12, 21], 
                           [ 12, 27, 45]])
assert np.array_equal(sub_gardens(example_garden), garden_correct)

### 3 Climbing skyscrapers. - 3p 

Bajtazar really liked your showcase and now wants you to help him with his little adventure. He wants to go and start climbing skyscapers in the city. Conveniently, they are all located in a block, next to each other, so he will just need to climb between them. You have to tell him how much rope he needs to prepare for every skyscraper to climb from it to the next one (except the last skyscraper, he will just climb down the stairs). Bajtazar needs rope both when climbing up and down.

Your are given an array `skyscrapers` of lenght `n` with the heights of skyscrapers in the block. You have to return the array `lines` of length `n-1`, where `lines[i]` is the amount of line Bajtazar needs to climb from skyscraper `i` to `i+1`.  

In [6]:
def climbing(skyscrapers: np.array) -> int:
    lines = skyscrapers[1:] - skyscrapers[:-1]
    lines = np.abs(lines)
    return lines

In [7]:
skyscrapers = np.array([1, 2, 6, 3, 2])

print(climbing(skyscrapers))
assert np.array_equal(climbing(skyscrapers), np.array([1, 4, 3, 1]))

[1 4 3 1]
