In [2]:
import numpy as np

def low_high_list(arr, treshold):
    np_arr = np.array(arr)
    check = np_arr > treshold

    check = np.array([1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 5, 1, 1, 2])
    args = list(zip(check[:-1], check[1:]))
    res = [prev for prev, next in args if prev != next]

    if res[-1] == check[-1]:
        return res
    else:
        return res + [check[-1]]

low_high_list([0,0,3,3,3,1,1,3,3], 2)

np.arange(6)[-3:]

array([3, 4, 5])

In [3]:
def low_high_list(arr, threshold = 0):
    arr = np.array(arr)
    check = arr > threshold
    args = list(zip(check[:-1], check[1:]))
    res = [prev for prev, next in args if prev != next]

    if len(res) == 0:
        return [arr[0] > threshold]
    elif res[-1] == check[-1]:
        return res
    else:
        return res + [check[-1]]
    
low_high_list([1,2])

[np.True_]

In [4]:
import cv2
import numpy as np

GREEN = (0, 255, 0)
RED = (255, 0, 0)

def draw_blurred_quadrilateral(img, p_list, color, girth):
  shifted = np.concat([p_list[-1:],p_list[:-1]]).astype(int)
  zip_list = list(zip(p_list, shifted))

  for (p1, p2) in zip_list:
    cv2.line(img, p1, p2, color, girth)
  
def draw_quadrilateral(img, p_list, color, girth):
  shifted = np.concat([p_list[-1:],p_list[:-1]]).astype(int)
  zip_list = list(zip(p_list, shifted))

  for (p1, p2) in zip_list:
    cv2.line(img, p1, p2, color, girth)

def draw_square(img, p1, p3, color, girth):
  p_matrix = np.vstack([p1, p3])
  new = (p_matrix * np.eye(2), p_matrix * np.array([0,1,1,0]).reshape(2,2))

  p2, p4 = list(map(lambda x: x[np.nonzero(x)], new))
  p4 = p4[::-1]

  p_list = np.array([p1, p2, p3, p4]).astype(int)
  draw_quadrilateral(img, p_list, color, girth)

def drawMarkers(img, corners, ids):
  if ids is None:
    return

  square_size = 7
  for i in range(ids.shape[0]):
    c = corners[i][0]
    id = ids[i][0]
    draw_quadrilateral(img, c.astype(int), GREEN, 3)
    draw_square(img, c[0] - (square_size // 2), c[0] + (square_size // 2), RED, 1)
    cv2.putText(img, f"{id}", c[0].astype(int), cv2.FONT_HERSHEY_SIMPLEX, 1, RED, 2)

In [5]:
from PIL import Image
import time

def PIL_show(img, colorspace = 'RGB'):
    if (colorspace != 'RGB'):
        color_trans = getattr(cv2, f'COLOR_{colorspace}2RGB')
        img = cv2.cvtColor(img, color_trans)
    pil_image = Image.fromarray(img)
    pil_image.show()

def detect_subpix(gray, corners, ids):
    if ids is not None:
        window_size = (5, 5)
        zero_zone = (-1, -1)
        criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

        refined_corners = []
        for corner in corners:
            corner = np.array(corner, dtype = np.float32) 
            refined = cv2.cornerSubPix(gray, corner, window_size, zero_zone, criteria)
            refined_corners.append(refined)

    return refined_corners

def visualize_corners(img, corners, ids = None, verbosity = 0):
    img0 = img.copy()

    if verbosity > 0:
        drawMarkers(img0, corners, ids)
    else:
        cv2.aruco.drawDetectedMarkers(img0, corners)

    if verbosity > 1:
        for x, y in np.array(corners).reshape(8, 2).astype(int):
            cv2.circle(img0, (x, y), 3, RED, cv2.FILLED)
            PIL_show(img0)
            time.sleep(1)
    else:
        PIL_show(img0)
        time.sleep(3)

def detect_corners(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_6X6_250)
    parameters = cv2.aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(dictionary, parameters)

    corners, ids, _ = detector.detectMarkers(gray)
    ret = ids is not None and len(ids) == 1

    if ret:
        visualize_corners(img, corners)

    corners = np.array(corners).reshape(-1, 1, 2)
    return ret, corners


ret, corners = detect_corners(cv2.imread('assets/textures/marker_0.png'))
print(corners)

[[[ 25.  25.]]

 [[224.  25.]]

 [[224. 224.]]

 [[ 25. 224.]]]


In [15]:
tvecs = np.array([1, 2, 3]).reshape(3,1)
vec = np.vstack([tvecs[[2, 0]], [[0]]])
print(vec)
theta = np.pi - angle
print(vec)
print(rot_M(2, theta) @ vec) 
print('')

[[3]
 [1]
 [0]]


NameError: name 'angle' is not defined